version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/default.conf:ro
      - ./html:/var/www/html:ro
    restart: always