version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: run.Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: run.Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    env_file:
      - .env

volumes:
  postgres_data:
    driver: local
